server:
  port: 10001

springdoc:
  default-consumes-media-type: application/x-www-form-urlencoded
  default-produces-media-type: application/json;charset=UTF-8

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/example-swagger?characterEncoding=UTF-8
    username: hsjung
    password: hs1234@!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true