server:
  port: 10003   # server port

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/example_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: my_password
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mariadb
      database-platform: org.hibernate.dialect.MariaDBDialect

application:
  security:
    jwt:
      secret-key: 763979244226452948404D6351665468576D5A7134743777217A25432A462D4A
      expiration: 60000 # 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days